FROM node:lts-stretch-slim

RUN npm i docsify-cli -g --registry=https://registry.npm.taobao.org

ONBUILD COPY docs /srv/docsify/docs
ONBUILD WORKDIR /srv/docsify

CMD ["/usr/local/bin/docsify", "serve", "docs"]